// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Dcs_PYY7xRUFOb0MYV4LFi0bBNyWSS0',
    appId: '1:823849432335:web:516e5bc87412dd0ff73a7a',
    messagingSenderId: '823849432335',
    projectId: 'ourchat-9c309',
    authDomain: 'ourchat-9c309.firebaseapp.com',
    storageBucket: 'ourchat-9c309.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARxm56ggCl9_AtJFoZqF5k-fcZP9Ti1OM',
    appId: '1:823849432335:android:a1a21f55b3b88af2f73a7a',
    messagingSenderId: '823849432335',
    projectId: 'ourchat-9c309',
    storageBucket: 'ourchat-9c309.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Dcs_PYY7xRUFOb0MYV4LFi0bBNyWSS0',
    appId: '1:823849432335:web:243c9999e4a6ae7af73a7a',
    messagingSenderId: '823849432335',
    projectId: 'ourchat-9c309',
    authDomain: 'ourchat-9c309.firebaseapp.com',
    storageBucket: 'ourchat-9c309.firebasestorage.app',
  );
}
